name: Sync GHCR Calico images with Docker Hub
on:
  schedule:
    # run every 12h
    - cron:  '0 */12 * * *'
  workflow_dispatch:

jobs:
  mirror-calico:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry (ghcr)
        run: echo ${{ secrets.GHCR_PASSWORD }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
      - name: Fetch latest Calico release
        id: fetch-latest-release
        run: |
          set -exuo pipefail

          calico_version=$(curl \
                             -H 'Accept: application/vnd.github+json' \
                             'https://api.github.com/repos/projectcalico/calico/releases' | \
                           jq '.[].tag_name' | \
                           sed -e 's/"\(.*\)"/\1/g' | \
                           sort --version-sort --reverse | \
                           head -n1)

          echo "Found version: ${calico_version}"

          pushd .github/workflows/
          ./mirror-calico.sh "${calico_version}"
          popd
