name: Get the latest Runc release for main
on:
  schedule:
    - cron:  '50 7 * * 4'
  workflow_dispatch:

jobs:
  get-runc-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch latest Runc release
        id: fetch-latest-release
        run: |
          git clone https://github.com/opencontainers/runc
          # Get the newest runc version, including official releases and rc versions.
          # We need some sed tweaks like adding underscore, sort, and trim the underscore again,
          # so that sort -V can give the newest version including non-rc versions.
          versionMain=$(git -C runc ls-remote --tags origin | cut -f2 | sed '/-/!{s/$/_/}' | sed -n "/refs\/tags\/v[0-9]*\.[0-9]*\.[0-9]*/s/^refs\/tags\/v//p" |grep -v '\{\}$' | sort -ruV | sed 's/_$//' | head -n1)
          commitMain="$(git -C runc rev-parse v${versionMain})"
          versionMain="${versionMain//-/_}"
          rm -rf runc
          echo "VERSION_MAIN=${versionMain}" >>"${GITHUB_OUTPUT}"
          echo "COMMIT_MAIN=${commitMain}" >>"${GITHUB_OUTPUT}"
          echo "BASE_BRANCH_MAIN=main" >>"${GITHUB_OUTPUT}"
      - name: Set up Flatcar SDK
        id: setup-flatcar-sdk
        run: .github/workflows/setup-flatcar-sdk.sh
      - name: Apply patch for main
        id: apply-patch-main
        env:
          TARGET: main
          BASE_BRANCH: ${{ steps.fetch-latest-release.outputs.BASE_BRANCH_MAIN }}
          VERSION_NEW: ${{ steps.fetch-latest-release.outputs.VERSION_MAIN }}
          COMMIT_HASH: ${{ steps.fetch-latest-release.outputs.COMMIT_MAIN }}
          PATH: ${{ steps.setup-flatcar-sdk.outputs.path }}
          PACKAGES_CONTAINER: ${{ steps.setup-flatcar-sdk.outputs.PACKAGES_CONTAINER }}
          SDK_NAME: ${{ steps.setup-flatcar-sdk.outputs.SDK_NAME }}
        run: .github/workflows/runc-apply-patch.sh
      - name: Create pull request for main
        uses: peter-evans/create-pull-request@v4
        if: steps.apply-patch-main.outputs.UPDATE_NEEDED == 1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ steps.fetch-latest-release.outputs.BASE_BRANCH_MAIN }}
          branch: runc-${{ steps.fetch-latest-release.outputs.VERSION_MAIN }}-main
          author: Flatcar Buildbot <buildbot@flatcar-linux.org>
          committer: Flatcar Buildbot <buildbot@flatcar-linux.org>
          title: Upgrade Runc in main from ${{ steps.apply-patch-main.outputs.VERSION_OLD }} to ${{ steps.fetch-latest-release.outputs.VERSION_MAIN }}
          commit-message: Upgrade Runc in main from ${{ steps.apply-patch-main.outputs.VERSION_OLD }} to ${{ steps.fetch-latest-release.outputs.VERSION_MAIN }}
          body: Upgrade Runc in main from ${{ steps.apply-patch-main.outputs.VERSION_OLD }} to ${{ steps.fetch-latest-release.outputs.VERSION_MAIN }}
          labels: main
